### ISSUE TITLE
error in fxn repeating_digits

### ISSUE THREAD

**Issue by vijaybarve** [thiloshon/Biodiversity#1]
While running from ````sample_function.R```` encountered following error:

````
> dat <- rgbif::occ_data(scientificName = 'Ursus americanus')
> flagged_dat <- repeating_digits(dat) 

 Error in 1:dim(gbif_data)[1] : argument of length 0 

````

**Comment by thiloshon** [comment]
Fixed in the latest commit. 

flagged_dat <- repeating_digits(dat) should have been
flagged_dat <- repeating_digits(dat$data)
